import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {build} from 'esbuild';
const root=new URL('../',import.meta.url);
const source=readFileSync(new URL('worker/index.js',root),'utf8');
let built=source;
built=built.replace('const portfolioPage = "__PORTFOLIO_HTML__";','const portfolioPage = '+JSON.stringify(readFileSync(new URL('assets/portfolio.html',root),'utf8'))+';');
built=built.replace('const researchPage = "__RESEARCH_HTML__";','const researchPage = '+JSON.stringify(readFileSync(new URL('assets/research.html',root),'utf8'))+';');
built=built.replace('const accountPage = "__ACCOUNT_HTML__";','const accountPage = '+JSON.stringify(readFileSync(new URL('assets/account.html',root),'utf8'))+';');
const accountBundle=await build({entryPoints:[new URL('assets/account.jsx',root).pathname],bundle:true,minify:true,platform:'browser',format:'iife',write:false,define:{'process.env.NODE_ENV':'"production"'}});
built=built.replace('const accountScript = "__ACCOUNT_JS__";',()=> 'const accountScript = '+JSON.stringify(accountBundle.outputFiles[0].text)+';');
const tradeBundle=await build({entryPoints:[new URL('assets/manual-trade.js',root).pathname],bundle:true,minify:true,platform:'browser',format:'iife',write:false,define:{'process.env.NODE_ENV':'"production"'}});
built=built.replace('const manualTradeScript = "__MANUAL_TRADE_JS__";','const manualTradeScript = '+JSON.stringify(tradeBundle.outputFiles[0].text)+';');
built=built.replace('const calloutWatchScript = "__CALLOUT_WATCH_JS__";','const calloutWatchScript = '+JSON.stringify(readFileSync(new URL('assets/callout-watch.js',root),'utf8'))+';');
const report=new URL('research/latest.json',root);
if(existsSync(report))built=built.replace('const latestEvidence=null;','const latestEvidence='+JSON.stringify(JSON.parse(readFileSync(report,'utf8')))+';');
const workerBundle=await build({stdin:{contents:built,resolveDir:new URL('worker/',root).pathname,sourcefile:'scope-worker.js',loader:'js'},bundle:true,platform:'browser',format:'esm',target:'es2022',write:false});
writeFileSync(new URL('dist/server/index.js',root),workerBundle.outputFiles[0].text);
