import {readFileSync,writeFileSync,existsSync} from 'node:fs';
const root=new URL('../',import.meta.url);
const source=readFileSync(new URL('worker/index.js',root),'utf8');
const heroArt=readFileSync(new URL('assets/scope-instrument.webp',root)).toString('base64');
if(!source.includes('__HERO_ASSET__'))throw Error('Missing hero asset slot');
let built=source.replaceAll('__HERO_ASSET__','data:image/webp;base64,'+heroArt);
built=built.replace('const chamberShader = "";','const chamberShader = '+JSON.stringify(readFileSync(new URL('assets/chamber.frag',root),'utf8'))+';');
built=built.replace('const portfolioPage = "__PORTFOLIO_HTML__";','const portfolioPage = '+JSON.stringify(readFileSync(new URL('assets/portfolio.html',root),'utf8'))+';');
const report=new URL('research/latest.json',root);
if(existsSync(report))built=built.replace('const latestEvidence=null;','const latestEvidence='+JSON.stringify(JSON.parse(readFileSync(report,'utf8')))+';');
writeFileSync(new URL('dist/server/index.js',root),built);
