import assert from 'node:assert/strict';
import worker,{compareSample,buildPaperTrades,persistCampaignEvidence} from '../worker/index.js';
const launch={kind:'launch',at:0,mint:'one',name:'A',symbol:'A',marketCapSol:27};
const trade=(at,priceSol,extra={})=>({kind:'trade',at,mint:'one',priceSol,marketCapSol:27.5,side:'buy',solAmount:.1,trader:'t1',...extra});
const results=compareSample([launch,trade(100,2),trade(500,2),trade(5500,3)]);
assert.equal(results.length,2240);
const row=results.find(x=>x.entryRule==='c30-d500-raw-x112'&&x.exitRule==='time5');
assert.equal(row.closed,1);assert.equal(row.unresolved,0);
assert.ok(Math.abs(row.netSol-(.002*(3*.95/(2*1.05)-1)-.00002))<1e-12);
const collected=compareSample([launch,trade(100,2),trade(500,2),trade(5500,3)],{collectOutcomes:new Set(['c30-d500-raw-x112|time5'])}).find(x=>x.entryRule==='c30-d500-raw-x112'&&x.exitRule==='time5');
assert.equal(collected.outcomes.length,1);assert.ok(Math.abs(collected.outcomes[0]-row.netSol)<1e-12);
const missing=results.find(x=>x.entryRule==='c30-d500-raw-x112'&&x.exitRule==='time15');
assert.equal(missing.closed,0);assert.equal(missing.unresolved,1);assert.equal(missing.netSol,-.00202);
const sixty=results.find(x=>x.entryRule==='c30-d500-raw-x112'&&x.exitRule==='time60');
assert.equal(sixty.closed,0);assert.equal(sixty.unresolved,1);
const stagedResults=compareSample([launch,trade(100,2),trade(500,2),trade(5500,3),trade(30500,2.2)]);
const staged=stagedResults.find(x=>x.entryRule==='c30-d500-raw-x112'&&x.exitRule==='scale125-time30');
assert.equal(staged.closed,1);assert.ok(Math.abs(staged.netSol-(.002*(.5*(3*.95/(2*1.05))+.5*(2.2*.95/(2*1.05))-1)-.00002))<1e-12);
assert.equal(compareSample([launch,trade(400,1)]).every(x=>x.closed===0),true);
const fake={...launch,mint:'two',at:10};
const duplicates=compareSample([launch,fake,trade(100,1),trade(500,1),trade(5500,2),{...trade(100,1),mint:'two'},{...trade(600,1),mint:'two'},{...trade(5600,2),mint:'two'}]);
assert.equal(duplicates.find(x=>x.entryRule==='c30-d500-raw-x112'&&x.exitRule==='time5').closed,1);
const paper=buildPaperTrades([launch,trade(100,1,{trader:'a'}),trade(900,1.05,{trader:'b'}),trade(2500,1.1,{trader:'c'}),trade(3500,1.7,{side:'sell',trader:'d'})]);
assert.equal(paper.length,1);assert.equal(paper[0].status,'closed');assert.equal(paper[0].submittedTransaction,false);assert.equal(paper[0].killSwitch,'engaged');assert.equal(paper[0].exitReason,'1.5× target');
assert.ok(Math.abs(paper[0].netSol-(.002*(1.7*.95/(1.1*1.05)-1)-.00002))<1e-12);
const unresolved=buildPaperTrades([launch,trade(100,1,{trader:'a'}),trade(900,1.05,{trader:'b'}),trade(2500,1.1,{trader:'c'})]);
assert.equal(unresolved[0].status,'unresolved');assert.equal(unresolved[0].netSol,null);
const timed=buildPaperTrades([launch,trade(100,1,{trader:'a'}),trade(900,1.05,{trader:'b'}),trade(2500,1.1,{trader:'c'}),trade(18000,1.12,{trader:'d'})]);
assert.equal(timed[0].status,'closed');assert.equal(timed[0].exitReason,'15s time exit');assert.ok(timed[0].netSol<0);
assert.equal((await worker.fetch(new Request('https://test/api/forward-test'),{})).status,405);
assert.equal((await worker.fetch(new Request('https://test/api/forward-test',{method:'POST',headers:{Origin:'https://other'}}),{})).status,403);
assert.equal((await worker.fetch(new Request('https://test/api/forward-test',{method:'POST'}),{})).status,503);
const campaignStatus=await (await worker.fetch(new Request('https://test/api/campaign/status'),{})).json();
assert.deepEqual(campaignStatus,{available:false,targetLaunches:500,launches:0,trades:0,runs:0,progressPercent:0});
assert.deepEqual(await persistCampaignEvidence(null,{events:[]}),{state:'unavailable',storedLaunches:0,storedTrades:0});
const control=await (await worker.fetch(new Request('https://test/api/execution-status'),{})).json();
assert.deepEqual(control,{mode:'shadow',killSwitch:'engaged',liveTrading:false,signerLoaded:false,spendCapSol:0,transactionRoutes:0,walletIsolation:'market-data-only'});
const build=await (await worker.fetch(new Request('https://test/api/build'),{})).json();
assert.match(build.buildId,/^2026-09-\d{2}-r\d+$/);
const readiness=await (await worker.fetch(new Request('https://test/api/execution-readiness'),{})).json();
assert.equal(readiness.capitalUnlocked,false);assert.equal(readiness.gates.length,8);assert.equal(readiness.passed,1);assert.equal(readiness.policy.maxOrderSol,.002);
const snapshot=await (await worker.fetch(new Request('https://test/api/research-snapshot'),{})).json();
assert.equal(snapshot.analysis.available,false);assert.equal(snapshot.readiness.gates.length,8);
const canary=await worker.fetch(new Request('https://test/api/execution/canary',{method:'POST'}),{});
assert.equal(canary.status,423);assert.equal((await canary.json()).readiness.capitalUnlocked,false);
console.log('PASS: real-event comparator, paper fills, readiness interlock, canary rejection, wallet isolation, kill switch, and API guards');
